### ISSUE TITLE
Is there any way to filter metrics before sending to HostedGrafana?

### ISSUE THREAD

**Issue by chinwobble** [grafana/grafana-opentelemetry-dotnet#122]
# Question

Is there any way to filter metrics before sending to HostedGrafana?

My apps is sending tonnes of bucketed metrics for things like connecting to keyvault.
- I know in the adaptive metrics in the hosted Grafana side I can drop those metrics or drop certain labels.

The problem is that the adaptive metrics don't provide fine grained enough control over which label values I want to keep or drop.

metric `http_client_request_duration_seconds_bucket`
has a label called `server_address`. If `server_address = keyvault` I want to drop those series, if not I want to keep them.

**Comment by matt-hensley** [comment]
An official way of filtering metrics is being defined in the OpenTelemetry specification:
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#metricfilter

The `AddView` API in the OpenTelemetry .NET SDK allows for dropping metrics:
https://github.com/open-telemetry/opentelemetry-dotnet/tree/main/docs/metrics/customizing-the-sdk#drop-an-instrument

There is an overload that accepts a delegate that _may_ allow for conditionally dropping metric points. I'm traveling currently but will take a look next week.

**Comment by chinwobble** [comment]
@matt-hensley I've looked into the `addView` feature of open telemetry and it doesn't appear to be able to drop metrics by filtering on a specific label as I described in the OP.

**Comment by matt-hensley** [comment]
There is a proposal to add MetricProcessors to the specification, but it's not being actively worked on as of July 2024:
https://github.com/open-telemetry/opentelemetry-specification/issues/3617#issuecomment-2260864363

The only way to do filtering by metric label today is in Alloy/OTel Collector.

Examples:
[Alloy](https://grafana.com/docs/alloy/latest/reference/components/otelcol/otelcol.processor.filter/#drop-metrics-based-on-either-of-two-criteria)
[OTel Collector](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/processor/filterprocessor/README.md#examples)
